name: terraform-module-quality

on:
  workflow_call:
    inputs:
      lint_action_ref:
        required: false
        type: string
        default: v0
      branch_name_action_ref:
        required: false
        type: string
        default: v0

jobs:
  quality:
    name: quality
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Validate Branch Name
        if: github.event_name == 'pull_request'
        uses: launchbynttdata/actions-lcaf-branch_name@v0

      - name: Lint Terraform
        uses: launchbynttdata/actions-lcaf-terraform_lint@v0
